# Build the docker images using docker compose and the command below
#     docker-compose build
# Run the services in the docker compose using the command below
#     docker-compose up
# Run the services in the docker compose with hot reload using the command below
#     docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# Remove the services in the docker compose using the command below
#     docker-compose down

# Define the services and applications that make up your application.
services:
  frontend-app:
    build:
      context: ./ # Uses the current directory as the build context.
      dockerfile: ./infra/docker-images/reposensecloud-front/Dockerfile # Path to the directory containing the Dockerfile for the frontend application
    container_name: frontend_app
    ports:
      - 3000:3000 # Maps ports
    # environment:
    networks:
      - reposensecloud-network # Connects the frontend-app to the 'reposensecloud-network' network.

networks:
  reposensecloud-network: # Defines a network named 'reposensecloud-network'.
    driver: bridge # Uses the bridge driver for the network, which is the default and most common network type in Docker.