# Build the docker images using docker compose and the command below
#     docker-compose build
# Run the services in the docker compose using the command below
#     docker-compose up
# Run the services in the docker compose with hot reload using the command below
#     docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# Remove the services in the docker compose using the command below
#     docker-compose down

# Define the services and applications that make up your application.
services:
  frontend-app:
    build:
      context: ./
      dockerfile: ./infra/docker-images/rsc-frontend-image/Dockerfile
    container_name: rsc_frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - ./.env # docker-compose only works with .env file
    volumes:
      - ./frontend/:/app
    networks:
      - rsc-network
    environment:
      - REACT_APP_JOB_SERVICE_URL=http://job-service-app:3002/api/jobs

  user-service-app:
    build:
      context: ./
      dockerfile: ./infra/docker-images/rsc-local-backend-image/Dockerfile
      args:
        PORT: ${USER_SVC_PORT}
        SERVICE_NAME: rsc-user-service
    container_name: rsc_user_service
    ports:
      - ${USER_SVC_PORT}:${USER_SVC_PORT}
    env_file:
      - ./.env # docker-compose only works with .env file
    volumes:
      - ./backend/:/app/backend
      - ~/.m2:/root/.m2
      - ~/.aws:/root/.aws # KIV not working
    networks:
      - rsc-network


  job-service-app:
    build:
      context: ./
      dockerfile: ./infra/docker-images/rsc-local-backend-image/Dockerfile
      args:
        PORT: ${JOB_SVC_PORT}
        SERVICE_NAME: rsc-job-service
    container_name: rsc_job_service
    ports:
      - ${JOB_SVC_PORT}:${JOB_SVC_PORT}
    env_file:
      - ./.env # docker-compose only works with .env file
    volumes:
      - ./backend/:/app/backend
      - ~/.m2:/root/.m2
      - ~/.aws:/root/.aws # KIV not working
    networks:
      - rsc-network

networks:
  rsc-network: # Defines a network named 'rsc-network'.
    driver: bridge # Uses the bridge driver for the network, which is the default and most common network type in Docker.