# Run the services in the docker compose using the command below
#     docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

# This docker-compose file is for mounting the volume to the container for hot reloading

# Define the services and applications that make up your application.
services:
  rsc-frontend-app:
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  rsc-user-service-app:
    volumes:
      - ./backend/rsc-user-service/target:/app/target
