AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CodePipeline to deploy resources (Lambda, EKS, Frontend) based on prebuilt artifacts in S3

Parameters:
  Stage:
    Type: String
    Default: dev # Deployment stage (e.g., dev, production)
  ArtifactBucket:
    Type: String
    Description: S3 bucket name where artifacts and ready file are stored

Resources:
  DeployPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeployPipelinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*
              - Effect: Allow
                Action:
                  - codebuild:BatchGetProjects
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - codebuild:BatchGetBuildBatches
                  - iam:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: "*"

  DeployCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DeployCodeBuildPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - eks:*
                  - lambda:*
                  - iam:*
                  - sqs:*
                  - batch:*
                  - ec2:*
                  - events:*
                  - cloudfront:*
                  - cloudformation:*
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ssm:GetParameter
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Resource: "*"

  DeployCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "DeployProject-${Stage}"
      ServiceRole: !GetAtt DeployCodeBuildRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Sub "${AWS::AccountId}.dkr.ecr.ap-southeast-1.amazonaws.com/rsc-cicd:latest"
        ImagePullCredentialsType: SERVICE_ROLE
        # Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ARTIFACT_BUCKET
            Value: !Ref ArtifactBucket
          - Name: STAGE
            Value: !Ref Stage
      Source:
        Type: S3
        # Manually override the build spec via AWS Console to use inline buildspec
        Location: rsc-shipment-bucket/deploy_buildspec.zip
      TimeoutInMinutes: 20

  DeployPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt DeployPipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: ReadyFileTrigger
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: S3
                Version: 1
              Configuration:
                S3Bucket: !Ref ArtifactBucket
                S3ObjectKey: !Sub "trigger/${Stage}.txt"
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: ReadyArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: RunDeployProject
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: ReadyArtifact
              RunOrder: 1
              Configuration:
                ProjectName: !Ref DeployCodeBuildProject
