service: api

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: java8
  region: ap-southeast-1

package:
  artifact: target/reposensecloud-api-1.0.0-SNAPSHOT.zip

functions:
  TestApi:
    name: my-test-api
    handler: com.hamburger.company.reposensecloud.api.handler.TestApiHandler::handleRequest
    events:
      - http:
          path: /api/test
          method: get