service: sqs-lambda-service

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - !GetAtt MyQueue.Arn
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-lambda-queue

functions:
  sqsProcessor:
    handler: handler.processMessage
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 5

plugins:
  - serverless-offline
