service: sqs-lambda-service

provider:
  name: aws
  runtime: java17
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
      Resource:
        - !GetAtt MyQueue.Arn
    - Effect: Allow
      Action:
        - batch:SubmitJob
        - batch:DescribeJobs
      Resource: "*"
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: sqs-lambda-queue

package:
  artifact: target/batch-queue-1.0-SNAPSHOT.jar

functions:
  sqsProcessor:
    handler: com.hamburger.Handler::handleRequest
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
          batchSize: 5

plugins:
  - serverless-offline
