name: build and upload to s3

on:
  workflow_run:
    workflows: ["tag on merge"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to access tags

      - name: Download tag artifact
        uses: actions/download-artifact@v4
        with:
          name: version-tag

      - name: Read tag from artifact
        id: tag
        run: |
          TAG=$(cat tag.txt)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          git fetch --tags
          git checkout $TAG

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build Frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Upload Frontend to S3
        env:
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          aws s3 cp --recursive frontend/build/ ${{ secrets.SHIPMENT_BUCKET }}/frontend/$TAG/

      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Build JARs
        working-directory: ./backend
        run: mvn clean install -DskipTests

      - name: Upload JARs to S3
        env:
          AWS_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          aws s3 cp backend/rsc-user-service/target/rsc-user-service-1.0-SNAPSHOT.jar s3://${{ secrets.SHIPMENT_BUCKET }}/backend/$TAG/rsc-user-service-1.0-SNAPSHOT.jar
          aws s3 cp backend/rsc-job-service/target/rsc-job-service-1.0-SNAPSHOT.jar s3://${{ secrets.SHIPMENT_BUCKET }}/backend/$TAG/rsc-job-service-1.0-SNAPSHOT.jar
          aws s3 cp backend/rsc-batch-job/target/rsc-batch-job-1.0-SNAPSHOT.jar s3://${{ secrets.SHIPMENT_BUCKET }}/backend/$TAG/rsc-batch-job-1.0-SNAPSHOT.jar
